### ISSUE TITLE
Jenkins error pushing config changes to stage (frankfurt)

### ISSUE THREAD

**Issue by alexgibson** [mozmar/www-config#21]
I'm pretty sure that each time I've pushed a config change to bedrock-stage, it has tried to do Frankfurt twice - and always fails the second time with a very useful Jenkins error:

https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/bedrock-stage/4/pipeline/

I'm assuming this is doing no harm, as the first attempt works - but seems like something we should probably investigate?

**Comment by pmac** [comment]
looks like a misconfiguration of stage in frankfurt. it's doing https -> http redirect. I'll fix shortly.

**Comment by pmac** [comment]
stage is now working properly in Frankfurt I believe. This should be fixed.

**Comment by alexgibson** [comment]
Thanks @pmac 👍
